name: Test Oracle SQL

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start Oracle XE container
        run: |
          docker run --name oracle-db -d -p 1521:1521 -p 5500:5500 -v ${{ github.workspace }}:/workspace -e ORACLE_PASSWORD=oracle gvenzl/oracle-xe
      - name: Run SQL tests
        run: bash tests/test_sql_oracle.sh
