CREATE TABLE DEPT
       (NUM_DEPT NUMBER(2) CONSTRAINT DEPT_NUM_DEPT_PK PRIMARY KEY,
	NOM_DEPT VARCHAR2(14) ,
	SITUACIO VARCHAR2(13) ) ;
CREATE TABLE EMP
       (NOM VARCHAR2(10) CONSTRAINT EMP_NOM_PK PRIMARY KEY,
	TASCA VARCHAR2(9),
	SALARI NUMBER(7,2),
	COMISSIO NUMBER(7,2),
	NUM_DEPT NUMBER(2) CONSTRAINT EMP_NUM_DEPT_FK REFERENCES DEPT);
INSERT INTO DEPT VALUES
	(10,'COMPTABILITAT','HOBBITERS');
INSERT INTO DEPT VALUES (20,'RECERCA','RIVENDELL');
INSERT INTO DEPT VALUES
	(30,'VENDES','BREE');
INSERT INTO DEPT VALUES
	(40,'MARQUETING','VILATUC');
INSERT INTO EMP VALUES
('BILBO','PRESIDENT',1800,NULL,10);
INSERT INTO EMP VALUES
('FRODO','CAP',1200,NULL,20);
INSERT INTO EMP VALUES
('SAM','VENEDOR',1000,10,30);
INSERT INTO EMP VALUES
('MERRY','VENEDOR',1000,0,30);
INSERT INTO EMP VALUES
('PIPPIN','GERENT',1100,NULL,40);
COMMIT;
